### ISSUE TITLE
TODO: issues to solve

### ISSUE THREAD

**Issue by Trinsdar** [Trinsdar/GT-4-Renewed#40]
- [x] Osmium chest crashes when jei is loaded - rei seems to have no issues
- [x] Chests don't render opening sequence
- [x] conveyor and pump modules don't render indent on current mode
- [ ] crafting module doesn't open gui on fabric
